### ISSUE TITLE
Invalid cpusubtype read for arm64e

### ISSUE THREAD

**Issue by Toilettrauma** [opa334/ChOma#10]
Hi everyone!
I compiled ct_bypass for arm64e, but when i'm trying to bypass it prints:
```
CoreTrust bypass eta s0n!!
Found 1 MachO slice.
File size 0x2131e0 bytes, MachO slice count 1.
Error: failed to find a valid, preferred macho.
Error: failed to extract preferred slice!
```
It checks cpusubtype as 0x80000002 and cannot find slice. Need to add ~CPU_SUBTYPE_MASK
I checked macho with otool and it prints:
```
ct_bypass_arm64e:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          2  0x80           2    20       1968 0x00200085
```

**Comment by Halo-Michael** [comment]
Why close this issues? I guess it's still happen?
![5E418133-FD04-4B50-9259-4DD9DAA201DB](https://github.com/opa334/ChOma/assets/45062120/32aea194-4bc1-4b0d-8513-b72ec377c830)

**Comment by Halo-Michael** [comment]
> Why close this issues? I guess it's still happen? ![5E418133-FD04-4B50-9259-4DD9DAA201DB](https://private-user-images.githubusercontent.com/45062120/294700722-32aea194-4bc1-4b0d-8513-b72ec377c830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzUwNzcsIm5iZiI6MTcwNDczNDc3NywicGF0aCI6Ii80NTA2MjEyMC8yOTQ3MDA3MjItMzJhZWExOTQtNGJjMS00YjBkLTg1MTMtYjcyZWMzNzdjODMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE3MjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYWY5MWFkOGMxZmFkM2ZhYzcwZGUzOThiMjk4YmM4NmI0ODMwOGMxMDY5MDE1MDljNTYwZWFlOGI4NDM5Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qcGQolv8dI9n_GAE-F8xLIcM2lgClPfP0gz93YgGP7Y)

Update: Really fixed in https://github.com/opa3
![3E76BCE0-EB0B-47B9-BC95-9FB7126BCF53](https://github.com/opa334/ChOma/assets/45062120/a055a8d8-4302-48bb-b90b-e8bd22412d31)
34/ChOma/commit/5d923d0fb742cca72dfcfcc820d1a1d55edcd67a.
