### ISSUE TITLE
Using an arbitrary TeamID

### ISSUE THREAD

**Issue by papamata1** [opa334/ChOma#5]
I try to set an arbitrary `TeamID` so I can inject a dylib to an arbitrary app with `opainject`. I updated`AppStoreCodeDirectory.h` with a Code Directory from the target app but when I use `opainject`, the kernel complains about the signature. Is there any step I am missing?

**Comment by alfiecg24** [comment]
You need to manually create a new template signature blob - it is hardcoded to match the original App Store CodeDirectory.

**Comment by opa334** [comment]
https://github.com/opa334/ChOma/blob/main/tests/ct_bypass/main.c#L127-L130 these have to be adjusted
