### ISSUE TITLE
[Q] Install IPA after CoreTrust applied

### ISSUE THREAD

**Issue by enty8080** [opa334/ChOma#6]
Hello @opa334 ,

I am sorry to bother you. Is it possible to install an IPA after applying `ct_bypass` to the app bundle inside. I was trying to do this but got `Failed to verify code signature of /var/ ... (and the extracted payload path)`. I applied the `ct_bypass` to it before so I don't understand why the signature is invalid. Shouldn't `ct_bypass` sign the binary?

If it is possible, can you please point me to the right direction?

P.S. So basically the question is, how to install IPA without TrollStore but instead applying the CoreTrust bug to it manually and installing using Sideloadly or Filza for example?

Thanks in advance,
Ivan Nikolskiy (@enty8080)

**Comment by alfiecg24** [comment]
You can’t install it using the standard installation procedure - installd will reject the app’s code signature as it isn’t vulnerable to the same bug as CoreTrust bug. This is the reason we don’t have an install method for 16.5.1-17.0 on A12+.

**Comment by enty8080** [comment]
@alfiecg24 I see. Thank you for explaining this to me.

**Comment by enty8080** [comment]
@alfiecg24 I just checked that I am on iOS 16.3.1. Is there a same reason why the IPA can't be installed?

**Comment by alfiecg24** [comment]
TrollStore mimics the installation process that installd normally performs, but it skips the validation part, and that’s why it can install the fake-signed apps.

**Comment by enty8080** [comment]
@alfiecg24 I have a question that is not relevant to this issue. I wrote an app that used `posix_spawn` to spawn an executable that should create a file at `/var/mobile`. All entitlements are present, `ct_bypass` applied and `posix_spawn` says that executable was launched. However, the file was not created. If the executable is ran outside of application, it works and creates a file. What may be a problem?

I used TrollStore's implementation of `rootSpawn` and this is the code of executable:

```
#import <Foundation/Foundation.h>

#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSString *filePath = @"/var/mobile/pwned";
        NSString *fileContents = @"This file has been pwned!";

        NSError *error;
        BOOL success = [fileContents writeToFile:filePath atomically:YES encoding:NSUTF8StringEncoding error:&error];
    }
    return 0;
}
```

These are entitlements for both app and executable:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>platform-application</key>
	<true/>
	<key>com.apple.private.security.no-container</key>
	<true/>
	<key>com.apple.private.security.container-required</key>
	<false/>
	<key>com.apple.private.security.container-manager</key>
	<true/>
	<key>com.apple.private.security.storage.AppDataContainers</key>
	<true/>
	<key>com.apple.private.security.storage.Photos</key>
	<true/>
	<key>com.apple.private.WebClips.read-write</key>
	<true/>
	<key>com.apple.private.necp.match</key>
	<true/>
	<key>com.apple.private.necp.policies</key>
	<true/>
	<key>com.apple.private.security.disk-device-access</key>
	<true/>
	<key>com.apple.private.skywalk.observe-stats</key>
	<true/>
	<key>com.apple.private.persona-mgmt</key>
    <true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.system-task-ports</key>
	<true/>
</dict>
</plist>
```

**Comment by alfiecg24** [comment]
Try using NSLog to see if it actually executes. Sandboxing around /var is very annoying and sometimes you just might not be able to create the file without a different entitlement.

**Comment by enty8080** [comment]
@alfiecg24 Oh yeah. Sorry for deleting the issue, I just fixed the problem.

**Comment by enty8080** [comment]
@alfiecg24 Do you know if process created by `posix_spawn` is getting killed if app crashes or exists? I assume not, since child process can survive is parent dies?

**Comment by ashoror** [comment]
Hi @enty8080, 

I have the same issue, and I didn't get it. Could you let me know what you fixed? It would be great!

Thanks!
